kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploymentname
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image:  nginx:alpine
        ports:
        - containerPort: 80
