apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: test
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31010
  selector:
    app: test